;   __________           .___      .__  .__                 _____  .__       .__     ___ ________________    ___
;   \______   \ ____   __| _/____  |  | |__| ____   ____   /     \ |__| ____ |__|   /  / \__    ___/     \   \  \
;    |     ___// __ \ / __ |\__  \ |  | |  |/    \ /  _ \ /  \ /  \|  |/    \|  |  /  /    |    | /  \ /  \   \  \
;    |    |   \  ___// /_/ | / __ \|  |_|  |   |  (  <_> )    Y    \  |   |  \  | (  (     |    |/    Y    \   )  )
;    |____|    \___  >____ |(____  /____/__|___|  /\____/\____|__  /__|___|  /__|  \  \    |____|\____|__  /  /  /
;                  \/     \/     \/             \/               \/        \/       \__\                 \/  /__/
;                                                                                      (c) 2018-2024 alf45star
;                                                                          https://github.com/alf45tar/PedalinoMini

[platformio]
default_envs  =	bpi-leaf-s3, lilygo-t-display-s3
workspace_dir = ${sysenv.TMPDIR}/PedalinoMini

[common]
lib_deps	=
  bxparks/AceButton@1.10.1
  bblanchon/ArduinoJson@7.2.0
  esphome/AsyncTCP-esphome@2.1.4
  esphome/ESPAsyncWebServer-esphome@3.2.2
  fastled/FastLED@3.7.4
  d03n3rfr1tz3/HC-SR04@1.1.2
  esphome/Improv@1.2.3
  majicdesigns/MD_REncoder@1.0.1
  h2zero/NimBLE-Arduino@1.4.2
  https://github.com/CNMAT/OSC@3.5.8
  dxinteractive/ResponsiveAnalogRead@1.2.1
  bodmer/TFT_eSPI@2.5.33
  fortyseveneffects/MIDI Library@5.0.2
  lathoub/AppleMIDI@3.3.0
  lathoub/BLE-MIDI@2.2
  lathoub/ipMIDI@1.0.3
  ryokosaka/Hello Drum@0.7.7
  adafruit/Adafruit ADS1X15@2.5.0

build_flags =
  -D PEDALINO_MINI
  -D PLATFORMIO_ENV=$PIOENV
  -D DEBUG_ESP_PORT=Serial
  -D CORE_DEBUG_LEVEL=5 
  ;ARDUHAL_LOG_LEVEL_WARN
  -D DIAGNOSTIC
  -D NVS
  ;-D SMARTCONFIG
  ;-D WPS


build_flags_bpi_leaf_s3 =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=0
  -D BATTERY
  -D BOARD_HAS_PSRAM
  -D USE_HSPI_PORT          ; use HSPI pins for TFT (instead of default VSPI pins), without this my display don't work on BPI Leaf S3
  -D USER_SETUP_LOADED
  -D ST7789_DRIVER
  -D TFT_WIDTH=240          ; 4 wire SPI display
  -D TFT_HEIGHT=320         ; 4 wire SPI display 
  -D TFT_RGB_ORDER=1
  -D TFT_MOSI=15			; data pin
  -D TFT_SCLK=16			; clock pin
  -D TFT_DC=12				; data/command pin 
  -D TFT_RST=37				; reset pin	
  -D TFT_CS=11				; chip select pin
  -D TFT_BL=-1              ; my display has no backlight pin, but if yours does, set it here
  -D TOUCH_CS=-1            ; my display has no touch, but if yours does, set it here
  -D LOAD_GLCD  
  -D LOAD_GFXFF
  -D SMOOTH_FONT      
  -D SPI_FREQUENCY=40000000 ; default is 40MHz, but if you have issues with display stability, try lowering this value (e.g. 20MHz or 10MHz)


build_flags_lilygo-t-display-s3 =
	-D ARDUINO_USB_CDC_ON_BOOT=1		;	Initialize the USB CDC (serial over USB) interface at the start of the program, even before the setup() function is executed.
										;	Communication over USB starts as soon as it powers on or resets, without waiting for the setup code to run.
    -D ARDUINO_USB_MODE=0				;	Disables CDC mode and turns on OTG.
										;	In order to flash the firmware you had to set the device manually into boot mode by pressing the BOOT and the RESET button.
										;	The device stay in download mode after flashing so you had to press the RESET button once more.
	-D BOARD_HAS_PSRAM					;	PSRAM not enabled by default
	-D BATTERY
	-D USER_SETUP_LOADED				;	TFT_eSPI configuration setup defined in platformio.ini
	-D ST7789_DRIVER
	-D INIT_SEQUENCE_3					; 	Using this initialisation sequence improves the display image
	-D CGRAM_OFFSET
	-D TFT_RGB_ORDER=TFT_RGB
	-D TFT_INVERSION_ON
	-D TFT_PARALLEL_8_BIT
	-D TFT_WIDTH=170
	-D TFT_HEIGHT=320
	-D TFT_CS=6
	-D TFT_DC=7
	-D TFT_RST=5
	-D TFT_WR=8
	-D TFT_RD=9
	-D TFT_D0=39
	-D TFT_D1=40
	-D TFT_D2=41
	-D TFT_D3=42
	-D TFT_D4=45
	-D TFT_D5=46
	-D TFT_D6=47
	-D TFT_D7=48
	-D TFT_BL=38
	-D TFT_BACKLIGHT_ON=HIGH
	-D LOAD_GLCD
	-D LOAD_GFXFF
	-D SMOOTH_FONT

[env]
platform                = espressif32@6.9.0
framework               = arduino
board_build.f_flash     = 80000000L
build_type              = release
lib_deps                = ${common.lib_deps}
monitor_speed           = 115200
monitor_filters         = esp32_exception_decoder, default


[env:lilygo-t-display-s3]
platform  	= espressif32@6.9.0
framework 	= arduino
board     	= lilygo-t-display-s3														;	https://docs.platformio.org/en/latest/boards/espressif32/lilygo-t-display-s3.html
board_build.partitions = src/partitions_lilygo-t-display-s3.csv
build_unflags = -D ARDUINO_USB_MODE=1													;	Undefine symbol defined in https://github.com/platformio/platform-espressif32/blob/master/boards/lilygo-t-display-s3.json
																						;	to avoid redefinition warnings
build_flags	= 	${common.build_flags}
				${common.build_flags_lilygo-t-display-s3}
lib_deps	= 	${common.lib_deps}
				adafruit/Adafruit TinyUSB Library@3.3.4									;	https://github.com/adafruit/Adafruit_TinyUSB_Arduino

[env:bpi-leaf-s3]
board                   = bpi_leaf_s3
board_build.partitions  = src/partitions_bpi_leaf_s3.csv
build_flags             = ${common.build_flags}
                          ${common.build_flags_bpi_leaf_s3}
lib_deps                = ${common.lib_deps}
                          adafruit/Adafruit TinyUSB Library@3.3.4
;upload_port  = /dev/cu.usbmodem14201
;monitor_port = ${env:bpi-leaf-s3.upload_port}
;build_type   = debug
;debug_speed  = 12000
;debug_tool   = esp-builtin
;debug_init_break = tbreak setup
board_build.mcu        = esp32s3
board_build.f_cpu      = 240000000L
board_build.flash_size = 8MB
board_build.flash_mode = dio
board_upload.flash_size = 8MB